nome = input("Escreva seu nome: ")
idade = input("Informe sua idade: ")
altura = input("Informe sua altura: ")
frase = print("\nNome: "+ nome + "\nIdade: " + str(idade) + " anos\nAltura: "+ str(altura))
print(type(nome))
print(type(idade))
print(type(altura))
